[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "serl_launcher"
version = "1.0.3"
dependencies = [
  "distrax",
  "einops",
  "flax",
  "jax",
  "tqdm",
  "imageio",
  "wandb",
  "safetensors",
]
requires-python = ">= 3.10"
license = "MIT"
[project.optional-dependencies]
infra = [
  "agentlace@https://github.com/moritzknaust/agentlace/archive/fc6be5208c9c89a805ed3ff4af2890e889ee3d69.zip",
]
